spring.application.name=Spring-OAuth2


spring.security.oauth2.client.registration.google.client-id=119742770732-d8u24ul64gun3ppnkhn3gegvej7f828l.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

